server:
  port: 8080

spring:
  application:
    name: DreamBuilder
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xhadlfkd?serverTime=UTC, jdbc:h2:mem:testdb
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

cos:
  key: cos12

jwt:
  issuer: 김영웅
  secret-key: iJgx1bclHYf9DGhRt6704NZnulCsksc9wEGCtjuLahUG8yQEXchr3QC2nJflUAPQ